name: Release PDF

on:
  release:
   types: [published]
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true
   
jobs:
  build:
    strategy:
      matrix:
        document: [setup, basics, embedded]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Creating PDF
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: ${{ matrix.document }}
        root_file: |
            ${{ matrix.document }}.tex
      
    - name: Uploading PDF to release
      run: |
        cd ${{ matrix.document }}
        gh release upload ${{ github.event.release.tag_name || inputs.release }} ${{ matrix.document }}.pdf
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
