name: Makefile CI

on:
  release:
   types: [published]
  workflow_dispatch:
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Creating PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: |
            setup/setup.tex
            basics/basics.tex
            # embedded/embedded.tex
      
    - name: Uploading PDF to release
      run: ls
