name: Makefile CI

on:
  release:
   types: [published]
  workflow_dispatch:
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Creating PDF
      run: make all
      
    - name: Uploading PDF to release
      run: echo Done
