name: Release PDF

on:
  release:
   types: [published]
   
jobs:
  build:
    strategy:
      matrix:
        document: [setup, basics, embedded]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Creating PDF
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: ${{ matrix.document }}
        root_file: |
            ${{ matrix.document }}.tex
      
    - name: Uploading PDF to release
      run: |
        cd ${{ matrix.document }}
        gh release ${{ github.event.release.tag_name }} ${{ matrix.document }}/${{ matrix.document }}.pdf
