name: Makefile CI

on:
  release:
   types: [published]
  workflow_dispatch:
   
jobs:
  build:
    strategy:
      matrix:
        document: [setup, basics, embedded]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Creating PDF
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: ${{ matrix.document }}
        root_file: |
            ${{ matrix.document }}.tex
      
    - name: Uploading PDF to release
      run: |
        cd ${{ matrix.document }}
        ls

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.document }}
        path: ${{ matrix.document }}/${{ matrix.document }}.pdf

